cse112-sp22-group4/Electric-Pomato

- .github/workflows/deploy.yml
- README.md
- source/js/WelcomeMessage.js
trying to get it to deploy to cse112-sp22-group4 instead of cse110-wi21-group21
> Fix deployment

- package.json
> Update package.json repo urls

- source/js/TaskList.js
- source/js/backend.js
> Add backend functions

- source/js/BreakPrompt.js
- source/js/app.js
> Changed localStorage calls to new functions (app.js, breakPrompt.js)

- .github/workflows/deploy.yml
- package-lock.json
- package.json
> Add JSDocs to deployment

- source/js/components/EditableTaskListBody.js
> Fix issue with new task item content being reset when editing a previous set task.

- .github/workflows/lint.yml
Take 2 #78 
Don't delete this branch yet
> fix workflow errors

- .github/workflows/lint.yml
> Fix workflow errors 

- source/app.html
- source/index.html
Closes #15 
Home button was already added as part of the menu icons (Thanks Steven)
Removed the links on the Electric Pomato titles to the homepage
> Remove old home links

- source/js/backend.js
- source/js/components/StartButtons.js
- source/js/scripts/app.js
Fix small bug where settings-related values in local storage are cleared at the end of a session.
> fix clearing settings data at end of session

- source/js/components/MenuIcons.js
pipeline demo commit 
this commit is really cool and stuff
> test commit

- source/js/components/MenuIcons.js
Reverts cse112-sp22-group4/Electric-Pomato#115
> Revert "test commit"

- package-lock.json
- source/app.html
- source/index.html
- source/js/components/MenuIcons.js
- source/scss/main.scss
Fix the styling for the menu icons to be more responsive on different screen dimensions.
> add responsive menu icon styling

- source/js/components/WelcomeMessage.js
> Update edit name button styling

- source/js/components/FinishTaskButton.js
> Revise finish task button popup text

- cypress/integration/Settings-test.js
- cypress/integration/TaskTime-test.js
Testing for serviceWorker bug fix
> wait for service worker to register

- source/js/components/SettingsModal.js
closes #180 - small bug where the revert settings button doesn't work for icons
> fix settings bug

- source/js/components/TimerUI.js
- source/scss/app.scss
Closes issue #184 
Remove the timer hover size increase when the timer is running
> Remove timer hover behavior when running

- source/__tests__/EditableTaskList.test.js
- source/js/components/EditableTaskListInput.js
Closes #192 
Change behavior of enter button on mobile to just exit the input so the user can edit pomos and add task using the button
> Fix enter on mobile bug 

- specs/adrs/051022-frontend-decisions.md
- specs/adrs/052822-sprint3-adr.md
> last few link errors
